services:
  frontend:
    build:
      context: .
      dockerfile: aqa-client/Dockerfile
      args:
        NEXT_PUBLIC_API_URL_V2: ${NEXT_PUBLIC_API_URL_V2:-http://host.docker.internal:8000/graphql}
        BACKEND_URL: ${BACKEND_URL:-http://host.docker.internal:8000/graphql}
        BACKEND_API_URL: ${BACKEND_API_URL:-http://host.docker.internal:8000}
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://host.docker.internal:8000/graphql}
      - BACKEND_API_URL=${BACKEND_API_URL:-http://host.docker.internal:8000}
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: aqa-backend-nestjs/Dockerfile
    network_mode: "host"
    environment:
      # These will fall back to your .env file's values
      - DB_TYPE
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # postgres:
  #   image: postgres:14-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: jnhbgvfc
  #     POSTGRES_DB: aqa
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s

  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3001:3000"

  # cadvisor:
  #   image: google/cadvisor:latest
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "81:80"
  #     - "443:443"
  #   depends_on:
  #     - frontend
  #     - backend

volumes:
  postgres_data: {}
